name: binkstoreap
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.3
  countup: ^0.1.4
  iconsax: ^0.0.8
  curved_navigation_bar: ^1.0.3
  animated_text_kit: ^4.2.1
  flutter_datetime_picker: ^1.5.1
  flutter_rounded_date_picker: ^2.0.2
  intl: ^0.17.0
  firebase_core: ^1.19.2
  firebase_analytics: ^9.2.0
  firebase_analytics_web: ^0.4.1
  firebase_app_check: ^0.0.6+17
  firebase_auth: ^3.4.2
  cloud_firestore: ^3.3.0
  cloud_functions: ^3.3.2
  firebase_storage: ^10.3.2
  firebase_dynamic_links: ^4.3.2
  firebase_app_installations: ^0.1.1+2
  firebase_database: ^9.0.19
  firebase_remote_config: ^2.0.12
  file_picker: ^4.6.1
  image_picker: ^0.8.5+3
  flutter_format_money_vietnam: ^0.0.2
  lottie: ^1.3.0
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  fonts:
    - family: Recoleta
      fonts:
        - asset: assets/fonts/Recoleta/Recoleta-Thin.ttf
          style: normal
          weight: 100
        - asset: assets/fonts/Recoleta/Recoleta-Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/Recoleta/Recoleta-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/Recoleta/Recoleta-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/Recoleta/Recoleta-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/Recoleta/Recoleta-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/Recoleta/Recoleta-Black.ttf
          style: normal
          weight: 900
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/Urbanist-Thin.ttf
          style: normal
          weight: 100
        - asset: assets/fonts/Urbanist/Urbanist-ExtraLight.ttf
          style: normal
          weight: 200
        - asset: assets/fonts/Urbanist/Urbanist-Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/Urbanist/Urbanist-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/Urbanist/Urbanist-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/Urbanist/Urbanist-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/Urbanist/Urbanist-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/Urbanist/Urbanist-ExtraBold.ttf
          style: normal
          weight: 800
        - asset: assets/fonts/Urbanist/Urbanist-Black.ttf
          style: normal
          weight: 900  
    - family: BeVietnamPro
      fonts:
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-Thin.ttf
          style: normal
          weight: 100
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-ExtraLight.ttf
          style: normal
          weight: 200
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-ExtraBold.ttf
          style: normal
          weight: 800
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-Black.ttf
          style: normal
          weight: 900  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/logo.png"
assets:
  - lib/assets/
  - lib/assets/colors/
  - lib/assets/cardRevenue.png
