// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoAzXL9GUY6royKhZ2ZiNQLTRCt69ALWQ',
    appId: '1:1055369430536:web:75f1246a2b92647a49b3bd',
    messagingSenderId: '1055369430536',
    projectId: 'binkstoreapp',
    authDomain: 'binkstoreapp.firebaseapp.com',
    databaseURL: 'https://binkstoreapp-default-rtdb.firebaseio.com',
    storageBucket: 'binkstoreapp.appspot.com',
    measurementId: 'G-YSKXD7C72S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtfHhy3L3i1mryqUzRWa1MctXeUHeKkvY',
    appId: '1:1055369430536:android:a68c03f245128ce949b3bd',
    messagingSenderId: '1055369430536',
    projectId: 'binkstoreapp',
    databaseURL: 'https://binkstoreapp-default-rtdb.firebaseio.com',
    storageBucket: 'binkstoreapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_1U3kOWf-9n6DCxjJtyIIUp-NFpQdHOo',
    appId: '1:1055369430536:ios:e3b0cc5e817f939449b3bd',
    messagingSenderId: '1055369430536',
    projectId: 'binkstoreapp',
    databaseURL: 'https://binkstoreapp-default-rtdb.firebaseio.com',
    storageBucket: 'binkstoreapp.appspot.com',
    androidClientId: '1055369430536-45b20bod0isj3tki83sq45c1enopnbgr.apps.googleusercontent.com',
    iosClientId: '1055369430536-b135t0miqhftnuck3tuv8a7vfnj7jha3.apps.googleusercontent.com',
    iosBundleId: 'com.example.binkstoreap',
  );
}
